export const ACCOUNT_CONSTANTS = {
  ACCOUNT: 'Account',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'Your email',
  NAME_LABEL: 'Name',
  NAME_PLACEHOLDER: 'Your name',
  FIELD_STUDY_LABEL: 'Field study',
  FACULTY_NAME_LABEL: 'Faculty name',
  PROGRAM_STUDY_LABEL: 'Program study',
  PROGRAM_STUDY_PLACEHOLDER: 'Your program study',
  FACULTY_NAME_PLACEHOLDER: 'Your faculty name',
  YEAR_STUDY_PLACEHOLDER: 'Your study year',
  YEAR_STUDY_LABEL: 'Study year',
  FIELD_STUDY_PLACEHOLDER: 'Your field study',
  FINANCIAL_STATUS_LABEL: 'Financial status',
  FINANCIAL_STATUS_PLACEHOLDER: 'Your financial status',
}
