export const USERS_CONSTANTS = {
  USERS: 'Users',
  UPDATE: 'Update',
  FACULTY: 'Faculty name',
  FACULTY_PLACEHOLDER: 'FIESC',
  UPDATE_USERS: 'Update users',
  UPLOAD_STUDENTS: '1. Upload students',
  UPLOAD_SECRETARIES: '2.  Upload secretaries',
  UPDATE_USERS_CANCEL: "No don't update it",
  UPLOAD_ERROR: 'Upload users failed',
  UPLOAD_SUCCESS: 'Upload users success',
  UPLOAD_INFO: 'After submit old users will be deleted automatically',
  DRAG_USERS: 'Drag file with users here or click to select files',
  CONCATENATE: 'Concatenate the name with the first name',
}
