export const HOME_CONSTANTS = {
  CREATE: 'Create',
  REASON: 'Reason',
  APPROVE: 'Approve',
  APPROVE_CERTIFICATE: 'Approve certificate',
  REJECT: 'Reject',
  REJECT_REASON: 'Reject reason',
  REJECT_REASON_PLACEHOLDER: 'Your reject reason',
  REJECT_CERTIFICATE: 'Reject certificate',
  CLOSE: 'Close',
  REASON_PLACEHOLDER: 'Your reason',
  TITLE: 'Recent certificates',
  CREATE_CERTIFICATE: 'Create certificate',
  NOTIFY_USER: 'Notify the user email about the changed status',

  APPROVED: 'Aprobat',
  REJECTED: 'Respins',
  IN_PROGRESS: 'In procesare',
  DOWNLOAD_CERTIFICATE: 'Download certificate',
}
